name: 'Run Fourmolu'
description: 'Check formatting of Haskell code with Fourmolu'
inputs:
  pattern:
    required: false
    description: >
      Glob pattern that are used to find source files to format. It is
      possible to specify several patterns by putting each on a new line.
    default: |
      **/*.hs
      **/*.hs-boot
  follow-symbolic-links:
    required: false
    description: >
      Whether to follow symbolic links.
    default: true
  extra-args:
    required: false
    description: >
      Extra arguments to pass to Fourmolu.
  version:
    required: false
    description: >
      The version number of Fourmolu to use. Defaults to "latest". Example
      version numbers -- `0.13.0.0`, `0.10.1.0`, etc. See
      https://github.com/fourmolu/fourmolu/releases for a list of all releases.
      Note that formatting changes in later versions of Fourmolu are not
      necessarily backwards-compatible.  You are recommended to specify the
      version of fourmolu you wish to use.
    default: latest
runs:
  using: 'node16'
  main: 'dist/index.js'
