name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macOS-latest
          # - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Disable core.autocrlf on Windows
        if: runner.os == 'Windows'
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: ./.
        # with:
        #   working-directory: ./test-code/
